FROM ghcr.io/cirruslabs/flutter:stable

USER root

RUN yes | sdkmanager --licenses >/dev/null \
    && sdkmanager \
        "platforms;android-34" \
        "platforms;android-35" \
        "ndk;28.2.13676358" \
        "cmake;3.22.1"

RUN flutter doctor -v